AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket and SQS queue

Parameters:
    BucketName:
        Type: String
        Description: Name of the S3 bucket

    QueueName:
        Type: String
        Description: Name of the SQS queue

Resources:
    # SQS image queue
    ImageQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Ref QueueName

    # S3 Bucket
    ImageBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref BucketName

            # Send SQS image queue message when object created
            NotificationConfiguration:
                QueueConfigurations:
                    - Event: "s3:ObjectCreated:*"
                      Queue: !GetAtt ImageQueue.Arn

    # Policy to allow bucket to send message
    SQSPolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            Queues:
                - !Ref ImageQueue
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: s3.amazonaws.com
                      Action: sqs:SendMessage
                      Resource: !GetAtt ImageQueue.Arn
                      Condition:
                          ArnLike:
                              aws:SourceArn: !Sub "arn:aws:s3:::${BucketName}"

Outputs:
    QueueArn:
        Value: !GetAtt ImageQueue.Arn
