tags:
  student-id: "s2264323"
  course: "gcu-cloudPlatformDevelopment"
  application: "labelAndFaceDetectionSystem"

resources:
  ec2:
    upload-image: 
      name: "ec2-upload-s2264323"
      config:
        ami-name: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
        instance-profile: ""
        instance-type: "t3.micro"
        min_count: 1
        max_count: 1

  s3:
    image-bucket:
      name: "bucket-images-2264323"
      config:

  lambda:
    image-detection: 
      name: "lambda-detection-s2264323"
    send-email:
      name: "lambda-email-s2264323"
  sqs:
    notify-image:
      name: "queue-images-s2264323"
  sns:
    email-topic:
      name: "email-topic-s2264323"
  dynamodb:
    images-db:
      name: "dynamodb-images-s2264323"
  rekognition:
    image-detection:
      name: "rekognition-images-s2264323"

iam:
  ec2:
    upload-image:
      name: "bucket-images-role-2264323"
  lambda:
    image-detection:
      name: "lambda-detection-role-s2264323"
    send-email:
      name: "lambda-email-role-s2264323"

