tags:
  student-id: "s2264323"
  course: "gcu-cloudPlatformDevelopment"
  application: "labelAndFaceDetectionSystem"

email: "ebury300@caledonian.ac.uk"

resources:
  ec2:
    upload-image: 
      name: "ec2-upload-s2264323"
      config:
        ami-name: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
        instance-profile: ""
        instance-type: "t3.micro"
        min_count: 1
        max_count: 1
  s3:
    image-bucket:
      name: "bucket-images-2264323"
      config:
  lambda:
    image-detection: 
      name: "lambda-detection-s2264323"
      role: ""
      runtime: "python3.14"
      handler: "lambda_handler"
    send-email:
      name: "lambda-email-s2264323"
      role: ""
      runtime: "python3.14"
      handler: "lambda_handler"
  sqs:
    notify-image:
      name: "queue-images-s2264323"
  sns:
    email-topic:
      name: "email-topic-s2264323"
  dynamodb:
    images-db:
      name: "dynamodb-images-s2264323"
      partition-key: "name"
      partition-key-type: "S"
  rekognition:
    image-detection:
      name: "rekognition-images-s2264323"
  cloudformation:
    image-bucket-queue:
      name: "stack-images-s2264323"